// src/lib/components/footer/Footer.svelte
<script lang="ts">
	import content from '$lib/content/content.json';
	const githubLink = content.general.socials.github;
</script>

<footer class="p-2 flex flex-col items-center justify-center">
	<span class="text-base"
		>made by <a class="text-app-yellow" href={githubLink} target={'_blank'} rel="noreferrer"
			>perryd01</a
		></span
	>
	<span class="text-sm">using SvelteKit and TailwindCSS</span>
</footer>

// components/footer.tsx
import Container from "./container";
import { EXAMPLE_PATH } from "../lib/constants";

const Footer = () => {
  return (
    <footer className="bg-neutral-50 border-t border-neutral-200">
      <Container>
        <div className="py-28 flex gap-4 flex-col lg:flex-row items-center text-neutral-900 font-medium text-lg lg:text-xl">
          <a href="https://miklosdaniel.hu">miklosdaniel.hu</a>
          <a
            href="https://twitter.com/daniel_miklos"
            target={"_blank"}
            rel="noreferrer"
          >
            Twitter
          </a>
          <a
            href="https://linkedin.com/in/miklos-daniel/"
            target={"_blank"}
            rel="noreferrer"
          >
            Linkedin
          </a>
          <a
            href="https://github.com/perryd01"
            target={"_blank"}
            rel="noreferrer"
          >
            Github
          </a>
          <a
            href="https://instagram.com/miklosdaniel.hu"
            target={"_blank"}
            rel="noreferrer"
          >
            Instagram
          </a>
        </div>
      </Container>
    </footer>
  );
};

export default Footer;
